## 排序算法
### 插入排序思想
* 从第二个元素开始，每个元素和前一个的元素进行比较，如果小于前一个元素，则调换位置；接着和前前一个元素比较，直至大于前一个元素或者不存在前一个元素时，比较结束
#### 插入排序效率
O(n2)
### 归并排序思想
* 分治法  
#### 归并排序效率
* O(nlogn)

In [1]:
def sort(list1, mode='insertion sorting'):
    list1 = list1.copy()
    if mode == 'insertion sorting':
        for i in range(1,len(list1)):
            ii = i
            while list1[ii] < list1[ii-1]:        
                temp = list1[ii]
                list1[ii] = list1[ii-1]
                list1[ii-1] = temp
                ii = ii-1
                if ii == 0:
                    break
        return list1
    elif mode == 'merge sorting':
        def merge(a1,a2):
            '''
            把a1,a2合并为一个排序好的序列
            a1 & a2: 两个已经排序好的list
            '''
            l1 = list()
            i, ii = 0, 0
            while i<len(a1) and ii < len(a2):
                if a1[i]<a2[ii]:
                    l1.append(a1[i])
                    i += 1
                else:
                    l1.append(a2[ii])
                    ii += 1
            if i<len(a1):
                l1.extend(a1[i:])
            else:
                l1.extend(a2[ii:])
            return l1
        def merge_sort(l1):
            if len(l1)>1:
                mid = len(l1)//2
                a1 = merge_sort(l1[:mid])
                a2 = merge_sort(l1[mid:])
                return merge(a1,a2)
            return l1
        return merge_sort(list1)


In [2]:
import numpy as np

In [3]:
list1 = np.random.permutation(20000)

In [4]:
list1[:5]

array([ 3390,  6441, 13606,  5265,  5091])

In [5]:
%%time
l1 = sort(list1)

CPU times: user 45.1 s, sys: 1.46 ms, total: 45.1 s
Wall time: 45.2 s


In [6]:
list1[:20]

array([ 3390,  6441, 13606,  5265,  5091, 11849, 18236,  8970,  5498,
        4057, 11199, 14358,  7800, 15345,  8756, 11750, 12372, 18185,
       13828,  6055])

In [7]:
l1[:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
%%time
l2 = sort(list1,mode='merge sorting')

CPU times: user 118 ms, sys: 997 µs, total: 119 ms
Wall time: 117 ms


In [9]:
l2[:20]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]