https://blog.csdn.net/baimafujinji/article/details/51151851

In [2]:
import numpy as npy
from sklearn import linear_model, datasets
from sklearn.cross_validation import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import accuracy_score, classification_report

In [3]:
iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features.
Y = iris.target

In [5]:
type(X),type(Y)

(numpy.ndarray, numpy.ndarray)

In [6]:
X.shape, Y.shape

((150, 2), (150,))

In [8]:
X[:5],Y[:5]

(array([[5.1, 3.5],
        [4.9, 3. ],
        [4.7, 3.2],
        [4.6, 3.1],
        [5. , 3.6]]), array([0, 0, 0, 0, 0]))

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [11]:
logreg = linear_model.LogisticRegression(C=1e5,  solver='lbfgs', multi_class='multinomial')
logreg.fit(X_train, y_train)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='multinomial', n_jobs=1, penalty='l2',
          random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
          warm_start=False)

In [12]:
prediction = logreg.predict(X_test)
print("accuracy score: ")
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

accuracy score: 
0.9
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.88      0.78      0.82         9
          2       0.83      0.91      0.87        11

avg / total       0.90      0.90      0.90        30



In [13]:
logreg_proba = logreg.predict_proba(X_test)
logreg_pred = logreg.predict(X_test)
for index in range (5):
    print(logreg_proba[index])
    print("Predict label:", logreg_pred[index])
    print("Correct label:", y_test[index])

[8.86511073e-26 5.64775369e-01 4.35224631e-01]
Predict label: 1
Correct label: 1
[9.99999942e-01 3.78533501e-08 2.02808786e-08]
Predict label: 0
Correct label: 0
[9.92889487e-70 8.98623548e-02 9.10137645e-01]
Predict label: 2
Correct label: 2
[4.40394840e-21 5.97659713e-01 4.02340287e-01]
Predict label: 1
Correct label: 1
[5.68223787e-43 2.90652338e-01 7.09347662e-01]
Predict label: 2
Correct label: 1
