https://mp.weixin.qq.com/s?__biz=MzI0ODcxODk5OA==&mid=2247498734&idx=2&sn=f175cc66caadb0c3bd1b85471259f59c&chksm=e99ec817dee94101da969734aaf0f36fb275825a2a4847932be7a9df5ea951fee134869c6314&scene=0#rd  



### 二. naive_bayes用法及简单案例

scikit-learn机器学习包提供了3个朴素贝叶斯分类算法：

GaussianNB(高斯朴素贝叶斯)  
MultinomialNB(多项式朴素贝叶斯)  
BernoulliNB(伯努利朴素贝叶斯)  

1.高斯朴素贝叶斯

调用方法为：sklearn.naive_bayes.GaussianNB(priors=None)。  
下面随机生成六个坐标点，其中x坐标和y坐标同为正数时对应类标为2，x坐标和y坐标同为负数时对应类标为1。通过高斯朴素贝叶斯分类分析的代码如下：

In [1]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
clf = GaussianNB()
clf.fit(X, Y)      
pre = clf.predict(X)

In [2]:
print("数据集预测结果:", pre)
print(clf.predict([[-0.8, -1]]))

数据集预测结果: [1 1 1 2 2 2]
[1]


In [3]:
clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y)) #增加一部分样本
print(clf_pf.predict([[-0.8, -1]]))

[1]


下面是朴素贝叶斯算法常见的属性和方法。

1) class_prior_属性  
观察各类标记对应的先验概率，主要是class_prior_属性，返回数组。代码如下：

In [4]:
print (clf.class_prior_)

[0.5 0.5]


2) class_count_属性

获取各类标记对应的训练样本数，代码如下：

In [5]:
print (clf.class_count_)

[3. 3.]


3) theta_属性

获取各个类标记在各个特征上的均值，代码如下：

In [6]:
print (clf.theta_)

[[-2.         -1.33333333]
 [ 2.          1.33333333]]


4) sigma_属性

获取各个类标记在各个特征上的方差，代码如下：

In [7]:
print (clf.theta_)

[[-2.         -1.33333333]
 [ 2.          1.33333333]]


5) fit(X, y, sample_weight=None)

训练样本，X表示特征向量，y类标记，sample_weight表各样本权重数组。

In [10]:
#设置样本不同的权重
clf.fit(X,Y,np.array([0.05,0.05,0.1,0.1,0.2,0.2]))
print(clf)  
print(clf.theta_)  
print(clf.sigma_) 

GaussianNB(priors=None)
[[-2.25 -1.5 ]
 [ 2.2   1.4 ]]
[[0.6875 0.25  ]
 [0.56   0.24  ]]


6) partial_fit(X, y, classes=None, sample_weight=None)

增量式训练，当训练数据集数据量非常大，不能一次性全部载入内存时，可以将数据集划分若干份，重复调用partial_fit在线学习模型参数，在第一次调用partial_fit函数时，必须制定classes参数，在随后的调用可以忽略。

In [11]:
X = np.array([[-1,-1], [-2,-2], [-3,-3], [-4,-4], [-5,-5], 
              [1,1], [2,2], [3,3]])  
y = np.array([1, 1, 1, 1, 1, 2, 2, 2])  
clf = GaussianNB()  
clf.partial_fit(X,y,classes=[1,2],
                sample_weight=np.array([0.05,0.05,0.1,0.1,0.1,0.2,0.2,0.2]))  
print (clf.class_prior_ )
print (clf.predict([[-6,-6],[4,5],[2,5]]) ) 
print (clf.predict_proba([[-6,-6],[4,5],[2,5]]))

[0.4 0.6]
[1 2 2]
[[1.00000000e+00 4.21207358e-40]
 [1.12585521e-12 1.00000000e+00]
 [8.73474886e-11 1.00000000e+00]]


可以看到点[-6,-6]预测结果为1，[4,5]预测结果为2，[2,5]预测结果为2。同时，predict_proba(X)输出测试样本在各个类标记预测概率值。

7) score(X, y, sample_weight=None)

返回测试样本映射到指定类标记上的得分或准确率。

In [12]:
pre = clf.predict([[-6,-6],[4,5],[2,5]])  
print (clf.score([[-6,-6],[4,5],[2,5]],pre))

1.0


最后给出一个高斯朴素贝叶斯算法分析小麦数据集案例，代码如下：